/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.Panel;
import Cocktail.*;
import function.*;
import java.io.IOException;
import javax.imageio.IIOException;

/**
 *
 * @author Dennis
 */
public class Hauptansichtneu extends javax.swing.JFrame {

    /**
     * Creates new form Hauptansichtneu
     */
    private LoadBufferedCocktails load = new LoadBufferedCocktails("0");
    private int AktuellAngezeigerCocktail=0;
    private Cocktail[] alleCocktails = new Cocktail[60];
    private boolean loadGeschehen=false;
    
    public Hauptansichtneu() {
        
        
        initComponents();
        Getränke.setVisible(false);
        Getränke2.setVisible(false);
        Ausgabefenster.setVisible(false);
        if (loadGeschehen!=true)
        {
            try{
                for(int i=1; i<45;i++){

                    alleCocktails[i-1]=load.CocktailErzeugen(i);
                }
                loadGeschehen=true;
            }
            catch (IIOException a){
                loadGeschehen=true;
            }
            loadGeschehen=true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ausgabefenster = new javax.swing.JPanel();
        zurückAusgabefenster = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Textfeld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Getränke2 = new javax.swing.JPanel();
        zurück2 = new javax.swing.JButton();
        cocktail4 = new javax.swing.JButton();
        cocktail5 = new javax.swing.JButton();
        cocktail6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rechtsButton1 = new javax.swing.JToggleButton();
        linksButton1 = new javax.swing.JToggleButton();
        Getränke = new javax.swing.JPanel();
        zurück = new javax.swing.JButton();
        cocktail1 = new javax.swing.JButton();
        cocktail2 = new javax.swing.JButton();
        cocktail3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        linksButton = new javax.swing.JToggleButton();
        rechtsButton = new javax.swing.JToggleButton();
        Hauptseite = new javax.swing.JPanel();
        AlkoholischeCocktailsButton = new javax.swing.JButton();
        BenutzerdefinierteCocktailsButton = new javax.swing.JButton();
        AlkoholfreieCocktailsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("alpha");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1025, 600));
        setMinimumSize(new java.awt.Dimension(1025, 600));
        setResizable(false);

        Ausgabefenster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zurückAusgabefenster.setText("Zürück");
        zurückAusgabefenster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückAusgabefensterActionPerformed(evt);
            }
        });
        Ausgabefenster.add(zurückAusgabefenster, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        jButton1.setText("Bestellen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Textfeld.setEditable(false);
        Textfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfeldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Textfeld, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 172, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Textfeld))
                .addContainerGap())
        );

        Ausgabefenster.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 740, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/CocktailMaschineohnepfeile.jpg"))); // NOI18N
        Ausgabefenster.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        Getränke2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zurück2.setText("Zürück");
        zurück2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurück2ActionPerformed(evt);
            }
        });
        Getränke2.add(zurück2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        cocktail4.setText("Cocktail 4");
        cocktail4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocktail4ActionPerformed(evt);
            }
        });
        Getränke2.add(cocktail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 140, 188));

        cocktail5.setText("Cocktail5");
        cocktail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocktail5ActionPerformed(evt);
            }
        });
        Getränke2.add(cocktail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 140, 188));

        cocktail6.setText("Cocktail6");
        cocktail6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocktail6ActionPerformed(evt);
            }
        });
        Getränke2.add(cocktail6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 140, 188));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/CocktailMaschinepfeil.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        Getränke2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        rechtsButton1.setText("jToggleButton1");
        rechtsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechtsButton1ActionPerformed(evt);
            }
        });
        Getränke2.add(rechtsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, 130));

        linksButton1.setText("jToggleButton1");
        linksButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linksButton1ActionPerformed(evt);
            }
        });
        Getränke2.add(linksButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 130));

        Getränke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zurück.setText("Zürück");
        zurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückActionPerformed(evt);
            }
        });
        Getränke.add(zurück, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        cocktail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/kleinCuba.jpg"))); // NOI18N
        cocktail1.setText("Cocktail1");
        cocktail1.setMaximumSize(new java.awt.Dimension(20, 23));
        cocktail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocktail1ActionPerformed(evt);
            }
        });
        Getränke.add(cocktail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 140, 188));

        cocktail2.setText("Cocktail2");
        cocktail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocktail2ActionPerformed(evt);
            }
        });
        Getränke.add(cocktail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 140, 188));

        cocktail3.setText("Cocktail3");
        cocktail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocktail3ActionPerformed(evt);
            }
        });
        Getränke.add(cocktail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 140, 188));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/CocktailMaschinepfeil.jpg"))); // NOI18N
        Getränke.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        linksButton.setText("jToggleButton1");
        linksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linksButtonActionPerformed(evt);
            }
        });
        Getränke.add(linksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 130));

        rechtsButton.setText("jToggleButton1");
        rechtsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechtsButtonActionPerformed(evt);
            }
        });
        Getränke.add(rechtsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, 130));

        Hauptseite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlkoholischeCocktailsButton.setText("Alkoholische Cocktails");
        AlkoholischeCocktailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkoholischeCocktailsButtonActionPerformed(evt);
            }
        });
        Hauptseite.add(AlkoholischeCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 200, 40));

        BenutzerdefinierteCocktailsButton.setText("Benutzerdefinierte Cocktails");
        Hauptseite.add(BenutzerdefinierteCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 180, 40));

        AlkoholfreieCocktailsButton.setText("Alkoholfreie Cocktails");
        AlkoholfreieCocktailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkoholfreieCocktailsButtonActionPerformed(evt);
            }
        });
        Hauptseite.add(AlkoholfreieCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/CocktailMaschine.jpg"))); // NOI18N
        Hauptseite.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hauptseite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Getränke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Getränke2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ausgabefenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hauptseite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Getränke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Getränke2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ausgabefenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlkoholischeCocktailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkoholischeCocktailsButtonActionPerformed
        Getränke.setVisible(true);
        Hauptseite.setVisible(false);
        
               // TODO add your handling code here:
    }//GEN-LAST:event_AlkoholischeCocktailsButtonActionPerformed

    private void AlkoholfreieCocktailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkoholfreieCocktailsButtonActionPerformed
        Getränke.setVisible(true);
        Hauptseite.setVisible(false);
        
    }//GEN-LAST:event_AlkoholfreieCocktailsButtonActionPerformed

    private void zurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückActionPerformed
        //Hauptansichtneu hauptansichtneu = new Hauptansichtneu();
        Getränke.setVisible(false);
        Hauptseite.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückActionPerformed

    private void zurück2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurück2ActionPerformed
        //Hauptansichtneu hauptansichtneu = new Hauptansichtneu();
        Getränke2.setVisible(false);
        Hauptseite.setVisible(true);
    }//GEN-LAST:event_zurück2ActionPerformed

    private void cocktail4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocktail4ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cocktail4ActionPerformed

    private void cocktail5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocktail5ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cocktail5ActionPerformed

    private void cocktail6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocktail6ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cocktail6ActionPerformed

    private void zurückAusgabefensterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückAusgabefensterActionPerformed
        Ausgabefenster.setVisible(false);
        Getränke.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückAusgabefensterActionPerformed

    private void linksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksButtonActionPerformed
        Getränke2.setVisible(true);
        Getränke.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_linksButtonActionPerformed

    private void rechtsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechtsButtonActionPerformed
        Getränke2.setVisible(true);
        Getränke.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rechtsButtonActionPerformed

    private void rechtsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechtsButton1ActionPerformed
        Getränke.setVisible(true);
        Getränke2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_rechtsButton1ActionPerformed

    private void linksButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksButton1ActionPerformed
        Getränke.setVisible(true);
        Getränke2.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_linksButton1ActionPerformed

    private void cocktail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocktail3ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke.setVisible(false);
    }//GEN-LAST:event_cocktail3ActionPerformed

    private void cocktail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocktail2ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke.setVisible(false);
               
        /*Cocktail zwei = null;
        try {
        zwei= load.CocktailErzeugen(2);
        }
        catch (IIOException a){
            
        }*/
        AktuellAngezeigerCocktail=2;
        Textfeld.setText(alleCocktails[1].getName()+": "+alleCocktails[1].getRezept());
        //eins.getRezept();
    }//GEN-LAST:event_cocktail2ActionPerformed

    private void cocktail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocktail1ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke.setVisible(false);
        
        /*        Cocktail eins = null;
        try {
        eins = load.CocktailErzeugen(1);
        }
        catch (IIOException a){
            
        }*/
        AktuellAngezeigerCocktail=1;
        Textfeld.setText(alleCocktails[0].getName()+ " " +alleCocktails[0].getPrintRezept(0));
        //eins.getRezept();
    }//GEN-LAST:event_cocktail1ActionPerformed

    private void TextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfeldActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_TextfeldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ModbusPrint newModbusPrint =new ModbusPrint(alleCocktails[AktuellAngezeigerCocktail-1].getRezept());
       try{
        newModbusPrint.printSPS();
       }
       catch (IOException a){
           System.out.println(a.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hauptansichtneu().setVisible(true);
                
                
                         }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlkoholfreieCocktailsButton;
    private javax.swing.JButton AlkoholischeCocktailsButton;
    private javax.swing.JPanel Ausgabefenster;
    private javax.swing.JButton BenutzerdefinierteCocktailsButton;
    private javax.swing.JPanel Getränke;
    private javax.swing.JPanel Getränke2;
    private javax.swing.JPanel Hauptseite;
    private javax.swing.JTextField Textfeld;
    private javax.swing.JButton cocktail1;
    private javax.swing.JButton cocktail2;
    private javax.swing.JButton cocktail3;
    private javax.swing.JButton cocktail4;
    private javax.swing.JButton cocktail5;
    private javax.swing.JButton cocktail6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton linksButton;
    private javax.swing.JToggleButton linksButton1;
    private javax.swing.JToggleButton rechtsButton;
    private javax.swing.JToggleButton rechtsButton1;
    private javax.swing.JButton zurück;
    private javax.swing.JButton zurück2;
    private javax.swing.JButton zurückAusgabefenster;
    // End of variables declaration//GEN-END:variables
}